// AUTO-GENERATED from VP_regulation.xlsx — DO NOT EDIT MANUALLY
export const regulationData = [
  {
    id: "construction_waste",
    name: "مخلفات البناء",
    stage: "المرحلة الأولى",
    color: "#EF4444",
    maxFine: 4000,
    articles: [
      {
        id: "construction_waste_1",
        seq: 1,
        text: "إلقاء مخلفات البناء أو الترميم في أراضي الغير أو الأماكن العامة",
        ref: "43",
        unit: "متر مكعب",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "construction_site_fencing",
    name: "تسوير مواقع الأعمال الإنشائية",
    stage: "المرحلة الأولى",
    color: "#F97316",
    maxFine: 4000,
    articles: [
      {
        id: "construction_site_fencing_2",
        seq: 2,
        text: "عدم وجود لوحة بمواقع البناء توضح بيانات الرخصة أو عدم صيانتها",
        ref: "4/2/15",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
      {
        id: "construction_site_fencing_3",
        seq: 3,
        text: "عدم تركيب السور المؤقت للمواقع الإنشائية",
        ref: "4/2/20",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
      {
        id: "construction_site_fencing_4",
        seq: 4,
        text: "تخزين مواد البناء ووضع المعدات والقيام بأعمال ورش البناء خارج حدود السور المؤقت",
        ref: "4/2/22",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
      {
        id: "construction_site_fencing_5",
        seq: 5,
        text: "عدم الالتزام بارتفاع السور المؤقت لمواقع الأعمال الإنشائية",
        ref: "4/2/23",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
      {
        id: "construction_site_fencing_6",
        seq: 6,
        text: "عدم تنفيذ السور المؤقت حسب المواصفات والتعليمات البلدية",
        ref: "4/2/24",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
      {
        id: "construction_site_fencing_7",
        seq: 7,
        text: "إقامة أو وضع الصناديق أو الأكشاك أو ما في حكمها في الأراضي الفضاء",
        ref: "4/2/27",
        unit: "عدد المواقع",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "إزالة المخالفة على نفقة المالك",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "construction_site_fencing_8",
        seq: 8,
        text: "تهالك السور المؤقت وعدم صيانته",
        ref: "4/2/28",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "temp_barriers",
    name: "الحواجز المؤقتة في مواقع العمل",
    stage: "المرحلة الأولى",
    color: "#F59E0B",
    maxFine: 12000,
    articles: [
      {
        id: "temp_barriers_9",
        seq: 9,
        text: "عدم التزام المقاول بوضع شعار الجهة الخدمية والمقاول واسمه على الحواجز المؤقتة",
        ref: "3/1",
        unit: "عدد الحواجز",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "temp_barriers_10",
        seq: 10,
        text: "ترك الحواجز المؤقتة بعد انتهاء الأعمال مباشرة لمدة 24 ساعة",
        ref: "3/34",
        unit: "عدد الحواجز",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 2400,
        fineMunicipality: 1800,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "temp_barriers_11",
        seq: 11,
        text: "استخدام حواجز مؤقتة متهالكة وتالفة وغير مدهونة وغير متماثلة",
        ref: "3/41",
        unit: "عدد الحواجز",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "temp_barriers_12",
        seq: 12,
        text: "عدم وضع الحواجز المؤقتة على صف واحد بطريقة منتظمة ومتلاصقة",
        ref: "3/42",
        unit: "عدد الحواجز",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 12000,
        fineMunicipality: 9000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "temp_barriers_13",
        seq: 13,
        text: "عدم توحيد نوع وحجم الحواجز المؤقتة",
        ref: "3/43",
        unit: "عدد الحواجز",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "building_under_construction",
    name: "تغطية المباني تحت الإنشاء",
    stage: "المرحلة الأولى",
    color: "#FBBF24",
    maxFine: 1600,
    articles: [
      {
        id: "building_under_construction_14",
        seq: 14,
        text: "عدم تغطية المباني تحت الإنشاء حسب المواصفات والتعليمات والمواقع التي تحددها البلدية",
        ref: "4/2/25",
        unit: "عدد المباني",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "lighting_poles",
    name: "أعمدة الإنارة",
    stage: "المرحلة الأولى",
    color: "#FDE68A",
    maxFine: 24000,
    articles: [
      {
        id: "lighting_poles_15",
        seq: 15,
        text: "إتلاف أعمدة الإنارة بأي وسيلة",
        ref: "3/13",
        unit: "عدد الأعمدة",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "lighting_poles_16",
        seq: 16,
        text: "وجود فانوس آيل للسقوط أو ساقط أو وجود أسالك وتمديدات إنارة مكشوفة",
        ref: "3/54",
        unit: "عدد الأعمدة",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 2000,
        fineMunicipality: 1500,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "lighting_poles_17",
        seq: 17,
        text: "وجود عداد كهرباء تابع للإنارة مصدوم أو ساقط أو محروق",
        ref: "3/55",
        unit: "عدد الأعمدة",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "abandoned_vehicles",
    name: "المركبات المهملة والتالفة",
    stage: "المرحلة الأولى",
    color: "#FB923C",
    maxFine: 500,
    articles: [
      {
        id: "abandoned_vehicles_18",
        seq: 18,
        text: "ترك المركبة التالفة أو الآلية المتعطلة في الساحات أو المواقف أو الشوارع لفترة تزيد عن 14 يوم",
        ref: "2/3/3",
        unit: "عدد المركبات",
        responsible: "مالك المركبة",
        notice: "لا ينطبق",
        severity: "غير جسيمة",
        period: "لا يوجد",
        fineAmana: 200,
        fineMunicipality: 200,
        punishment: "حجز المركبة",
        repeat: "لا يوجد",
      },
      {
        id: "abandoned_vehicles_19",
        seq: 19,
        text: "ترك المركبة المهملة في الساحات أو المواقف أو الشوارع لفترة تزيد عن 20 يوم",
        ref: "2/3/2",
        unit: "عدد المركبات",
        responsible: "مالك المركبة",
        notice: "لا ينطبق",
        severity: "غير جسيمة",
        period: "لا يوجد",
        fineAmana: 500,
        fineMunicipality: 500,
        punishment: "حجز المركبة",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "commercial_signs",
    name: "اللوحات التجارية",
    stage: "المرحلة الثانية",
    color: "#8B5CF6",
    maxFine: 3200,
    articles: [
      {
        id: "commercial_signs_20",
        seq: 20,
        text: "عدم مطابقة اللوحة التجارية للمواصفات والاشتراطات",
        ref: "1/2/2",
        unit: "عدد اللوحات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "commercial_signs_21",
        seq: 21,
        text: "عدم إزالة اللوحات التجارية بعد إلغاء الترخيص وتسليم الموقع بحالة جيدة",
        ref: "1/2/3",
        unit: "عدد اللوحات",
        responsible: "مالك السجل التجاري",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 3200,
        fineMunicipality: 2400,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "commercial_signs_22",
        seq: 22,
        text: "عدم صيانة أو إصلاح اللوحات التجارية التالفة",
        ref: "1/2/4",
        unit: "عدد اللوحات",
        responsible: "مالك السجل التجاري",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "restaurant_vents",
    name: "مداخن التهوية في المطاعم",
    stage: "المرحلة الثانية",
    color: "#EC4899",
    maxFine: 800,
    articles: [
      {
        id: "restaurant_vents_23",
        seq: 23,
        text: "مخالفة اشتراطات المداخن (وجود نظام تهوية ظاهر في الواجهات المطلة على الشوارع التجارية)",
        ref: "1/3/16",
        unit: "عدد المداخن",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "street_furniture",
    name: "أثاث الشوارع",
    stage: "المرحلة الثانية",
    color: "#A855F7",
    maxFine: 24000,
    articles: [
      {
        id: "street_furniture_24",
        seq: 24,
        text: "إتلاف ألعاب الأطفال أو مقاعد الجلوس أو المظلات أو الأكشاك أو الأرصفة أو الأسوار في الحدائق والساحات العامة",
        ref: "2/1/1",
        unit: "عدد الوحدات",
        responsible: "الفرد المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 1000,
        fineMunicipality: 1000,
        punishment: "التعويض بقيمة التالف",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "street_furniture_25",
        seq: 25,
        text: "إتلاف أي من الممتلكات العامة بأي وسيلة كانت خلال أعمال الحفريات",
        ref: "3/16",
        unit: "عدد الوحدات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "wall_graffiti",
    name: "الكتابات المشوهة للجدران",
    stage: "المرحلة الثانية",
    color: "#D946EF",
    maxFine: 800,
    articles: [
      {
        id: "wall_graffiti_26",
        seq: 26,
        text: "وجود كتابة أو ملصق على المباني أو واجهات المحلات/المنشآت المطلة على الشوارع التجارية",
        ref: "2/1/3",
        unit: "متر مربع",
        responsible: "للمالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "waste_containers",
    name: "الحاويات وتكدس النفايات",
    stage: "المرحلة الثانية",
    color: "#6366F1",
    maxFine: 8000,
    articles: [
      {
        id: "waste_containers_27",
        seq: 27,
        text: "العبث والإضرار بحاويات النفايات أو الأسوار المحيطة بها أو الأرضيات الصلبة التي ترتكز عليها",
        ref: "2/2/1",
        unit: "عدد الحاويات",
        responsible: "الفرد المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 1000,
        fineMunicipality: 1000,
        punishment: "التعويض بقيمة التالف",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_28",
        seq: 28,
        text: "عدم نظافة الحاويات التجارية",
        ref: "39",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_29",
        seq: 29,
        text: "تراكم النفايات السكنية أو التجارية وعدم التخلص منها أولاً بأول",
        ref: "44",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 2400,
        fineMunicipality: 1800,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_30",
        seq: 30,
        text: "وجود حاوية نفايات ممتلئة لأكثر من يوم",
        ref: "38",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 2400,
        fineMunicipality: 1800,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_31",
        seq: 31,
        text: "تعديل أو إتلاف الملصقات التعريفية بنوع النفايات على المركبة أو الحاوية",
        ref: "40",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_32",
        seq: 32,
        text: "إلقاء مواد مشتعلة أو قابلة للاشتعال في حاويات النفايات",
        ref: "61",
        unit: "عدد الحاويات",
        responsible: "فرد",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_33",
        seq: 33,
        text: "التخلص من النفايات في موقع غير مرخص من المركز",
        ref: "12",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_34",
        seq: 34,
        text: "التخلص من نفايات الحمأة في الأماكن غير المخصصة لها",
        ref: "52",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_35",
        seq: 35,
        text: "نبش حاويات النفايات وبعثرة محتوياتها (للأفراد)",
        ref: "24",
        unit: "عدد الحاويات",
        responsible: "فرد",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_36",
        seq: 36,
        text: "نبش حاويات النفايات وبعثرة محتوياتها (للمنشآت)",
        ref: "25",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "waste_containers_37",
        seq: 37,
        text: "وضع حاويات لجهات غير مرخصة في الأماكن العامة",
        ref: "49",
        unit: "عدد الحاويات",
        responsible: "منشأة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "إزالة الحاوية",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "street_excavation",
    name: "حفر الشوارع والطرق",
    stage: "المرحلة الثانية",
    color: "#3B82F6",
    maxFine: 24000,
    articles: [
      {
        id: "street_excavation_38",
        seq: 38,
        text: "عدم ردم الحفر وإعادة الحالة على ما كانت عليه بعد الانتهاء من العمل",
        ref: "3/6",
        unit: "متر مربع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "street_excavation_39",
        seq: 39,
        text: "إتلاف الشوارع المسفلتة والمرصوفة عند استخدام المعدات والآليات",
        ref: "3/11",
        unit: "متر مربع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "directional_signs",
    name: "اللوحات الإرشادية",
    stage: "المرحلة الثانية",
    color: "#0EA5E9",
    maxFine: 4000,
    articles: [
      {
        id: "directional_signs_40",
        seq: 40,
        text: "عدم صيانة السياج أو اللوحات الإرشادية أو التحذيرية عند منطقة العمل (لكل موقع)",
        ref: "3/9",
        unit: "عدد اللوحات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "sidewalks",
    name: "الأرصفة المتهالكة",
    stage: "المرحلة الثانية",
    color: "#06B6D4",
    maxFine: 24000,
    articles: [
      {
        id: "sidewalks_41",
        seq: 41,
        text: "إتلاف الأرصفة العامة أو أرصفة المنازل وحافاتها بأي وسيلة كانت",
        ref: "3/14",
        unit: "متر مربع",
        responsible: "مالك الترخيص",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "general_cleanliness",
    name: "النظافة العامة",
    stage: "المرحلة الثانية",
    color: "#14B8A6",
    maxFine: 24000,
    articles: [
      {
        id: "general_cleanliness_42",
        seq: 42,
        text: "عدم التزام أصحاب الشركات والمؤسسات بنظافة الساحات والممرات لمسافة 3 م",
        ref: "2/3/1",
        unit: "عدد المواقع",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_43",
        seq: 43,
        text: "تدني مستوى النظافة العامة للأرضيات أو الجدران أو الأسقف أو الواجهة",
        ref: "1/6/1",
        unit: "عدد المواقع",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_44",
        seq: 44,
        text: "ضخ المياه في مصائد السيول أو الأماكن غير المرخص بها",
        ref: "3/19",
        unit: "عدد المواقع",
        responsible: "المقاول / المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_45",
        seq: 45,
        text: "التخلص من النفايات في مجاري السيول والأودية أو الآبار أو الشواطئ",
        ref: "59",
        unit: "عدد المواقع",
        responsible: "فرد",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_46",
        seq: 46,
        text: "الحرق المكشوف للنفايات دون الحصول على الرخصة",
        ref: "13",
        unit: "عدد المواقع",
        responsible: "منشأة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_47",
        seq: 47,
        text: "التخلص من النفايات السكنية في الأماكن غير المخصصة لها",
        ref: "56",
        unit: "عدد المواقع",
        responsible: "فرد",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_48",
        seq: 48,
        text: "التخلص من النفايات الخضراء في الأماكن غير المخصصة لها",
        ref: "57",
        unit: "عدد المواقع",
        responsible: "فرد",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_49",
        seq: 49,
        text: "التخلص من النفايات السكنية ذات الأحجام الكبيرة في أوقات وأماكن غير محددة",
        ref: "58",
        unit: "عدد المواقع",
        responsible: "فرد",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_50",
        seq: 50,
        text: "رمي النفايات أثناء المشي أو من نوافذ المركبات أو المباني",
        ref: "97",
        unit: "عدد المواقع",
        responsible: "فرد",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 400,
        fineMunicipality: 300,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "general_cleanliness_51",
        seq: 51,
        text: "منع المفتش أو إعاقته عن تأدية أعماله",
        ref: "93",
        unit: "عدد المواقع",
        responsible: "منشأة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "illegal_storage",
    name: "التشوين",
    stage: "المرحلة الثانية",
    color: "#10B981",
    maxFine: 8000,
    articles: [
      {
        id: "illegal_storage_52",
        seq: 52,
        text: "التشوين خارج نطاق منطقة العمل المرخصة",
        ref: "3/28",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "material_transport",
    name: "نقل مواد البناء",
    stage: "المرحلة الثانية",
    color: "#22C55E",
    maxFine: 0,
    articles: [
      {
        id: "material_transport_53",
        seq: 53,
        text: "عدم تغطية صندوق حاويات مخلفات البناء أثناء النقل",
        ref: "-",
        unit: "عدد المركبات",
        responsible: "المقاول",
        notice: "—",
        severity: "—",
        period: "—",
        fineAmana: 0,
        fineMunicipality: 0,
        punishment: "—",
        repeat: "—",
      },
    ],
  },
  {
    id: "roof_hangars",
    name: "الهناجر المخالفة فوق السطوح",
    stage: "المرحلة الثانية",
    color: "#8B5CF6",
    maxFine: 1600,
    articles: [
      {
        id: "roof_hangars_54",
        seq: 54,
        text: "وجود أشاير حديدية أو أعمدة أو سواتر حديدية (شينكو) على أسوار الأسطح (الشوارع التجارية)",
        ref: "4/4/7",
        unit: "عدد المواقع",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "roof_hangars_55",
        seq: 55,
        text: "وجود أشاير حديدية أو أعمدة أو سواتر حديدية (شينكو) على أسوار الأسطح (المباني السكنية)",
        ref: "4/4/14",
        unit: "عدد المواقع",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "building_cladding",
    name: "تكسيات المباني المتهالكة",
    stage: "المرحلة الثانية",
    color: "#EC4899",
    maxFine: 1600,
    articles: [
      {
        id: "building_cladding_56",
        seq: 56,
        text: "وجود تشققات أو تلف في واجهات المباني أو صدأ واضح على المواد المعدنية",
        ref: "4/4/8",
        unit: "عدد المباني",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "ac_pipes",
    name: "مجاري وتمديدات التكييف",
    stage: "المرحلة الثانية",
    color: "#A855F7",
    maxFine: 1600,
    articles: [
      {
        id: "ac_pipes_57",
        seq: 57,
        text: "وجود تمديدات (كهربائية-صحية-ميكانيكية) ظاهرة بالواجهة الأمامية للمبنى (الشوارع التجارية)",
        ref: "4/4/9",
        unit: "عدد الوحدات",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "ac_pipes_58",
        seq: 58,
        text: "وجود وحدات تكييف منفصلة في الواجهات المطلة على الشارع (الشوارع التجارية)",
        ref: "4/4/10",
        unit: "عدد الوحدات",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "satellite_dishes",
    name: "أطباق الأقمار الاصطناعية",
    stage: "المرحلة الثانية",
    color: "#D946EF",
    maxFine: 1600,
    articles: [
      {
        id: "satellite_dishes_59",
        seq: 59,
        text: "وجود أطباق الأقمار الصناعية على واجهات المباني أو الشرفات (الشوارع التجارية)",
        ref: "4/4/11",
        unit: "عدد المباني",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "canopies",
    name: "المظلات والخيام",
    stage: "المرحلة الثانية",
    color: "#6366F1",
    maxFine: 1600,
    articles: [
      {
        id: "canopies_60",
        seq: 60,
        text: "وجود مظلات أو هناجر خارج حدود البناء",
        ref: "4/4/12",
        unit: "عدد المظلات",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "balcony_coverage",
    name: "تغطية الشرفات",
    stage: "المرحلة الثانية",
    color: "#3B82F6",
    maxFine: 1600,
    articles: [
      {
        id: "balcony_coverage_61",
        seq: 61,
        text: "تغطية الشرفات بهناجر أو مواد لا تتناسب مع شكل البناء أو سوء استخدام الشرفات",
        ref: "4/4/13",
        unit: "عدد الشرفات",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "advertising_boards",
    name: "اللوحات الإعلانية",
    stage: "المرحلة الثانية",
    color: "#0EA5E9",
    maxFine: 8000,
    articles: [
      {
        id: "advertising_boards_62",
        seq: 62,
        text: "عدم إزالة اللوحة أو الملصق الدعائي أو الإعلاني بعد انتهاء الترخيص",
        ref: "6/5",
        unit: "عدد اللوحات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "advertising_boards_63",
        seq: 63,
        text: "عدم توافق اللوحة الدعائية والإعلانية مع الكود العمراني أو التصميم المعتمد",
        ref: "6/6",
        unit: "عدد اللوحات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 2000,
        fineMunicipality: 1500,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "advertising_boards_64",
        seq: 64,
        text: "عدم الالتزام بالموقع المحدد للوحة الدعائية أو الإعلانية",
        ref: "6/7",
        unit: "عدد اللوحات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 2000,
        fineMunicipality: 1500,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "advertising_boards_65",
        seq: 65,
        text: "عدم معالجة أو صيانة اللوحة الدعائية والإعلانية",
        ref: "6/8",
        unit: "عدد اللوحات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "street_vendors",
    name: "البائعين الجائلين",
    stage: "المرحلة الثانية",
    color: "#06B6D4",
    maxFine: 800,
    articles: [
      {
        id: "street_vendors_66",
        seq: 66,
        text: "ممارسة البيع خارج المواقع المخصصة",
        ref: "8/4/1",
        unit: "عدد منافذ البيع",
        responsible: "للمخالف",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 250,
        fineMunicipality: 200,
        punishment: "مصادرة البضاعة",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "street_vendors_67",
        seq: 67,
        text: "العبث أو إتلاف منافذ البيع (إشعال النار أو مواقد اللهب أو إتلاف الأرصفة)",
        ref: "8/4/6",
        unit: "عدد منافذ البيع",
        responsible: "للمخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "إلغاء الترخيص وتعويض التالف",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "street_vendors_68",
        seq: 68,
        text: "عدم الالتزام بنظافة الموقع",
        ref: "8/4/8",
        unit: "عدد منافذ البيع",
        responsible: "للمخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 150,
        fineMunicipality: 100,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "warning_signs",
    name: "اللوحات التحذيرية",
    stage: "المرحلة الثانية",
    color: "#14B8A6",
    maxFine: 4000,
    articles: [
      {
        id: "warning_signs_69",
        seq: 69,
        text: "عدم صيانة السياج أو اللوحات الإرشادية أو التحذيرية عند منطقة العمل",
        ref: "3/9",
        unit: "عدد اللوحات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "public_restrooms",
    name: "دورات المياه العامة",
    stage: "المرحلة الثانية",
    color: "#10B981",
    maxFine: 0,
    articles: [
      {
        id: "public_restrooms_70",
        seq: 70,
        text: "تلف أو عدم دهان واجهات دورات المياه العامة",
        ref: "-",
        unit: "عدد دورات المياه",
        responsible: "البلدية",
        notice: "—",
        severity: "—",
        period: "—",
        fineAmana: 0,
        fineMunicipality: 0,
        punishment: "—",
        repeat: "—",
      },
      {
        id: "public_restrooms_71",
        seq: 71,
        text: "عدم نظافة دورات المياه العامة من الداخل",
        ref: "-",
        unit: "عدد دورات المياه",
        responsible: "البلدية",
        notice: "—",
        severity: "—",
        period: "—",
        fineAmana: 0,
        fineMunicipality: 0,
        punishment: "—",
        repeat: "—",
      },
    ],
  },
  {
    id: "curb_painting",
    name: "دهان البردورات",
    stage: "المرحلة الثانية",
    color: "#22C55E",
    maxFine: 0,
    articles: [
      {
        id: "curb_painting_72",
        seq: 72,
        text: "تلف أو عدم صيانة دهان حواجز الأرصفة الجانبية",
        ref: "-",
        unit: "متر طولي",
        responsible: "البلدية",
        notice: "—",
        severity: "—",
        period: "—",
        fineAmana: 0,
        fineMunicipality: 0,
        punishment: "—",
        repeat: "—",
      },
    ],
  },
  {
    id: "electrical_transformers",
    name: "المحولات الكهربائية في الشوارع",
    stage: "المرحلة الثالثة",
    color: "#64748B",
    maxFine: 4000,
    articles: [
      {
        id: "electrical_transformers_73",
        seq: 73,
        text: "وجود محولات كهربائية مكشوفة الأسالك في الشوارع",
        ref: "3/61",
        unit: "عدد المحولات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "illegal_speed_bumps",
    name: "المطبات العشوائية",
    stage: "المرحلة الثالثة",
    color: "#6B7280",
    maxFine: 8000,
    articles: [
      {
        id: "illegal_speed_bumps_74",
        seq: 74,
        text: "وضع مطبات صناعية بدون موافقة من الجهات المختصة",
        ref: "3/20",
        unit: "عدد المطبات",
        responsible: "المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "illegal_speed_bumps_75",
        seq: 75,
        text: "إزالة مطب نظامي لتهدئة السرعة دون إذن الجهات المختصة",
        ref: "3/35",
        unit: "عدد المطبات",
        responsible: "المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "illegal_speed_bumps_76",
        seq: 76,
        text: "عدم الالتزام بالمواصفات القياسية لوضع المطبات",
        ref: "3/60",
        unit: "عدد المطبات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 2400,
        fineMunicipality: 1800,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "green_spaces",
    name: "المساحات المخصصة للتشجير",
    stage: "المرحلة الثالثة",
    color: "#4B5563",
    maxFine: 8000,
    articles: [
      {
        id: "green_spaces_77",
        seq: 77,
        text: "نزع الحشائش والأشجار أو إتلاف أقفاص حماية الأشجار أو العبث بالحدائق العامة أو إتلاف النخيل أو شبكات الري",
        ref: "3/17",
        unit: "متر طولي",
        responsible: "المقاول / المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "road_markings",
    name: "عدم دهان العلامات الأرضية",
    stage: "المرحلة الثالثة",
    color: "#374151",
    maxFine: 4000,
    articles: [
      {
        id: "road_markings_78",
        seq: 78,
        text: "حواف الطرق والشوارع والمسارات وممرات المشاة غير محددة بوضوح",
        ref: "3/59",
        unit: "متر طولي",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "road_markings_79",
        seq: 79,
        text: "عدم إعادة وضع العلامات المرورية والدهانات بعد انتهاء المشروع",
        ref: "3/56",
        unit: "متر طولي",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 2400,
        fineMunicipality: 1800,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "road_markings_80",
        seq: 80,
        text: "العبث بعلامات الطريق أو العاكسات أو الشاخصات المنظمة لحركة السير",
        ref: "3/53",
        unit: "متر طولي",
        responsible: "المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "building_facades",
    name: "واجهات المباني المتهالكة",
    stage: "المرحلة الثالثة",
    color: "#475569",
    maxFine: 1600,
    articles: [
      {
        id: "building_facades_81",
        seq: 81,
        text: "وجود تشققات أو تلف في واجهات المباني أو صدأ واضح على المواد المعدنية",
        ref: "4/4/8",
        unit: "عدد المباني",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "telecom_poles",
    name: "أعمدة الاتصالات",
    stage: "المرحلة الثالثة",
    color: "#0F172A",
    maxFine: 40000,
    articles: [
      {
        id: "telecom_poles_82",
        seq: 82,
        text: "إنشاء برج جوال أو هوائي بدون ترخيص أو مخالف لما رخص له",
        ref: "4/3/1",
        unit: "عدد الأعمدة",
        responsible: "المشغل",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 40000,
        fineMunicipality: 30000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "telecom_poles_83",
        seq: 83,
        text: "وضع عربات متنقلة ومحولات كهربائية بدون ترخيص",
        ref: "4/3/3",
        unit: "عدد الأعمدة",
        responsible: "المشغل",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "telecom_poles_84",
        seq: 84,
        text: "عدم الالتزام بالارتفاع النظامي للأبراج",
        ref: "4/3/5",
        unit: "عدد الأعمدة",
        responsible: "المشغل",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "telecom_poles_85",
        seq: 85,
        text: "عدم الالتزام بالارتدادات النظامية في الأبراج",
        ref: "4/3/4",
        unit: "عدد الأعمدة",
        responsible: "المشغل",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "7 أيام",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "telecom_poles_86",
        seq: 86,
        text: "وجود تسريبات ديزل وغيرها من مولدات أبراج الاتصالات",
        ref: "4/3/7",
        unit: "عدد الأعمدة",
        responsible: "المشغل",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "utility_excavations",
    name: "مشاريع الخدمات والحفريات",
    stage: "المرحلة الثالثة",
    color: "#1E293B",
    maxFine: 40000,
    articles: [
      {
        id: "utility_excavations_87",
        seq: 87,
        text: "عدم إزالة المخلفات الناتجة من أعمال الحفر بعد الانتهاء",
        ref: "3/7",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_88",
        seq: 88,
        text: "عدم وضع سياج أرضي أو لوحات إرشادية عند منطقة العمل",
        ref: "3/8",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 24000,
        fineMunicipality: 18000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_89",
        seq: 89,
        text: "عدم وضع لوحات تحمل بيانات المشروع (لكل موقع)",
        ref: "3/10",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_90",
        seq: 90,
        text: "خلط الإسمنت على الإسفلت وأرصفة الشوارع",
        ref: "3/18",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_91",
        seq: 91,
        text: "إعاقة المشاة على الأرصفة بأي وسيلة كانت",
        ref: "3/22",
        unit: "عدد المواقع",
        responsible: "المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 15000,
        fineMunicipality: 15000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_92",
        seq: 92,
        text: "عدم نظافة موقع العمل أثناء العمل وبعد الانتهاء منه",
        ref: "3/26",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_93",
        seq: 93,
        text: "عدم وجود غطاء لفتحات التفتيش أو عدم صيانة الغطاء",
        ref: "3/33",
        unit: "عدد المواقع",
        responsible: "المقاول / الجهة المقدمة للخدمة",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_94",
        seq: 94,
        text: "إضافة أسفلت فوق الرصيف لتعديل المناسيب",
        ref: "3/37",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_95",
        seq: 95,
        text: "إضافة أسفلت فوق غرف التفتيش",
        ref: "3/38",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_96",
        seq: 96,
        text: "التعدي على الممتلكات العامة أثناء العمل",
        ref: "3/46",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 40000,
        fineMunicipality: 30000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_97",
        seq: 97,
        text: "رمي مخلفات الحفر بجانب الحفرية أثناء أعمال الحفر",
        ref: "3/51",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_98",
        seq: 98,
        text: "وضع دورات مياه مؤقتة خارج حدود الترخيص دون تصريح",
        ref: "3/52",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "utility_excavations_99",
        seq: 99,
        text: "عدم توفر لوحة لبيانات التصريح النظامية",
        ref: "3/57",
        unit: "عدد المواقع",
        responsible: "المقاول",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "1 يوم",
        fineAmana: 4000,
        fineMunicipality: 3000,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "agricultural_basins",
    name: "الأحواض الزراعية",
    stage: "المرحلة الثالثة",
    color: "#334155",
    maxFine: 8000,
    articles: [
      {
        id: "agricultural_basins_100",
        seq: 100,
        text: "نزع الحشائش والأشجار أو إتلاف أقفاص حماية الأشجار الصغيرة أو العبث بالحدائق العامة",
        ref: "3/17",
        unit: "عدد الأحواض",
        responsible: "المقاول / المخالف",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "سحب الأدوات",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "abandoned_buildings",
    name: "المباني المهجورة",
    stage: "المرحلة الثالثة",
    color: "#0284C7",
    maxFine: 8000,
    articles: [
      {
        id: "abandoned_buildings_101",
        seq: 101,
        text: "عدم إزالة الأبنية الخربة أو الآيلة للسقوط خلال شهرين من إبلاغ مالكها",
        ref: "4/2/11",
        unit: "عدد المباني",
        responsible: "المالك",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "60 يوم",
        fineAmana: 8000,
        fineMunicipality: 6000,
        punishment: "لا يوجد",
        repeat: "إزالة المبنى من قبل الأمانة",
      },
    ],
  },
  {
    id: "fences",
    name: "الأسوار",
    stage: "المرحلة الثالثة",
    color: "#0369A1",
    maxFine: 1600,
    articles: [
      {
        id: "fences_102",
        seq: 102,
        text: "وجود أسوار غير مكتملة البناء أو بها تشوهات أو تلف",
        ref: "4/4/15",
        unit: "متر طولي",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "abandoned_parks",
    name: "الحدائق والملاعب المهجورة",
    stage: "المرحلة الثالثة",
    color: "#075985",
    maxFine: 1000,
    articles: [
      {
        id: "abandoned_parks_103",
        seq: 103,
        text: "إتلاف المزروعات والنباتات والأشجار في الحدائق والساحات العامة",
        ref: "2/1/2",
        unit: "عدد الحدائق",
        responsible: "الفرد المخالف",
        notice: "لا ينطبق",
        severity: "غير جسيمة",
        period: "لا يوجد",
        fineAmana: 1000,
        fineMunicipality: 1000,
        punishment: "التعويض بقيمة التالف",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "vacant_land_fencing",
    name: "تسوير الأراضي البيضاء",
    stage: "المرحلة الثالثة",
    color: "#0C4A6E",
    maxFine: 180,
    articles: [
      {
        id: "vacant_land_fencing_104",
        seq: 104,
        text: "عدم تسوير أو تشجير محيط الأراضي في المناطق التي تحددها البلدية",
        ref: "4/2/14",
        unit: "متر طولي",
        responsible: "المالك",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 180,
        fineMunicipality: 160,
        punishment: "لا يوجد",
        repeat: "لا يوجد",
      },
    ],
  },
  {
    id: "electrical_wires",
    name: "الأعمدة والأسالك الكهربائية",
    stage: "المرحلة الثالثة",
    color: "#1D4ED8",
    maxFine: 2000,
    articles: [
      {
        id: "electrical_wires_105",
        seq: 105,
        text: "وجود فانوس آيل للسقوط أو ساقط أو وجود أسالك وتمديدات إنارة مكشوفة",
        ref: "3/54",
        unit: "عدد الوحدات",
        responsible: "المقاول",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 2000,
        fineMunicipality: 1500,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
  {
    id: "water_leaks",
    name: "تسرب المياه",
    stage: "المرحلة الثالثة",
    color: "#64748B",
    maxFine: 1600,
    articles: [
      {
        id: "water_leaks_106",
        seq: 106,
        text: "عدم إحكام تغطية خزانات المياه والصرف الصحي وغرف التفتيش أمام المحل / المنشأة",
        ref: "1/3/13",
        unit: "عدد الوحدات",
        responsible: "مالك الترخيص",
        notice: "لا ينطبق",
        severity: "جسيمة",
        period: "لا يوجد",
        fineAmana: 1600,
        fineMunicipality: 1200,
        punishment: "إغلاق المحل لحين معالجة المخالفة",
        repeat: "تضاعف الغرامة عند التكرار",
      },
      {
        id: "water_leaks_107",
        seq: 107,
        text: "تسرب أو تساقط المياه من أجهزة التكييف أو الثلاجات أو تمديدات البخار",
        ref: "1/6/9",
        unit: "عدد الوحدات",
        responsible: "مالك الترخيص",
        notice: "ينطبق",
        severity: "غير جسيمة",
        period: "14 يوم",
        fineAmana: 800,
        fineMunicipality: 600,
        punishment: "لا يوجد",
        repeat: "تضاعف الغرامة عند التكرار",
      },
    ],
  },
]

